server:
  port: 8081

spring:
  application:
    name: clinicas-service
  datasource:
      url: jdbc:mysql://localhost:3306/clinicas_db  # Cambiado a MySQL
      username: root  # Cambiado a 'root' o el usuario correspondiente
      password: 123456  # Cambia la contraseña a la correspondiente
      driver-class-name: com.mysql.cj.jdbc.Driver  # Driver para MySQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      citasService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10